version: "3.9"

services:
app:
    container_name: api
    image: api
    build:
        context: .
        dockerfile: Dockerfile
        target: runtime
    restart: always
    ports:
        - "8080:8080"
